### PR TITLE
Add locale to dockerfile

### PR DESCRIPTION
**Pull request by lalo**

### CODE REVIEW

**Comment by jackgerrits** [comment]
Why didn't the CI run? Could it have been the outage?

**Comment by lalo** [comment]
GitHub was somewhat laggy during that time of day so probably intermittent error. I’ll try to re-trigger to test before merging.


On Apr 3, 2020, at 9:32 AM, Jack Gerrits <notifications@github.com> wrote:

﻿

Why didn't the CI run?

**Comment by jackgerrits** [comment]
If you push an empty commit hopefully it should retrigger

**Comment by lalo** [comment]
Tested locally, this fixes bug #21

**Pull request merged**
